services:
  - type: web
    name: flask-postgress-mysql-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PGHOST
        value: dpg-d2japsvdiees73c09ajg-a
      - key: pGUSER
        value: asset_db_mcav_user
      - key: PGPASSWORD
        value: wtUYcIasEkpRhW94K9zG9y8mIkAm7KjY
      - key: PGDATABASE
        value: asset_db_mcav
