services:
  - type: web
    name: flask-postgress-mysql-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PGHOST
        value: dpg-d1oe80er433s73c8mpo0-a
      - key: pGUSER
        value: asset_db_mj7s_user
      - key: PGPASSWORD
        value: COv3fMv5rb2auV7qUFpf3XyiBex6qSsB
      - key: PGDATABASE
        value: asset_db_mj7s
